# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoilMoisture', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MacroSensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.FloatField()),
                ('Humidity', models.FloatField()),
                ('WaterLevel', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MicroSensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.addPlant')),
            ],
        ),
    ]
