# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-30 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoilMoisture', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MacroSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_time', models.DateField(auto_now=True)),
                ('Temperature', models.FloatField(null=True)),
                ('Humidity', models.FloatField(null=True)),
                ('WaterLevel', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MicroSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.addPlant')),
            ],
        ),
    ]
