# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20170827_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrosensor',
            name='read_time',
            field=models.DateField(auto_now=True),
        ),
    ]
